development:
  adapter: postgresql
  encoding: unicode
  database: course_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: course_test
  pool: 5
  host: localhost
